//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presto.BBVA.ServicioBanco {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://grupobbva.com.pe/portal_inmobiliario/", ConfigurationName="ServicioBanco.MS_BBVA_PORTAL_INMOBILIARIOPortType")]
    public interface MS_BBVA_PORTAL_INMOBILIARIOPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultaSaldos no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://grupobbva.com.pe/portal_inmobiliario/consultaSaldos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Presto.BBVA.ServicioBanco.consultaSaldos_Output consultaSaldos(Presto.BBVA.ServicioBanco.consultaSaldos_Input request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultaPrestamo no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://grupobbva.com.pe/portal_inmobiliario/consultaPrestamo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Presto.BBVA.ServicioBanco.consultaPrestamo_Output consultaPrestamo(Presto.BBVA.ServicioBanco.consultaPrestamo_Input request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/b402/")]
    public partial class consultaSaldosRq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ctHeaderRq headerField;
        
        private BodyConsultaSaldosRq bodyField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ctHeaderRq header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("header");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BodyConsultaSaldosRq body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/ps9/")]
    public partial class ctHeaderRq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string terminalLogicoField;
        
        private string terminalContableField;
        
        private string usuarioField;
        
        private string opcionAplicacionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string terminalLogico {
            get {
                return this.terminalLogicoField;
            }
            set {
                this.terminalLogicoField = value;
                this.RaisePropertyChanged("terminalLogico");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string terminalContable {
            get {
                return this.terminalContableField;
            }
            set {
                this.terminalContableField = value;
                this.RaisePropertyChanged("terminalContable");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string opcionAplicacion {
            get {
                return this.opcionAplicacionField;
            }
            set {
                this.opcionAplicacionField = value;
                this.RaisePropertyChanged("opcionAplicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/u360/")]
    public partial class cuotasAdicionales : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cuotaEneroField;
        
        private string cuotaFebreroField;
        
        private string cuotaMarzoField;
        
        private string cuotaAbrilField;
        
        private string cuotaMayoField;
        
        private string cuotaJunioField;
        
        private string cuotaJulioField;
        
        private string cuotaAgostoField;
        
        private string cuotaSetiembreField;
        
        private string cuotaOctubreField;
        
        private string cuotaNoviembreField;
        
        private string cuotaDiciembreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cuotaEnero {
            get {
                return this.cuotaEneroField;
            }
            set {
                this.cuotaEneroField = value;
                this.RaisePropertyChanged("cuotaEnero");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cuotaFebrero {
            get {
                return this.cuotaFebreroField;
            }
            set {
                this.cuotaFebreroField = value;
                this.RaisePropertyChanged("cuotaFebrero");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cuotaMarzo {
            get {
                return this.cuotaMarzoField;
            }
            set {
                this.cuotaMarzoField = value;
                this.RaisePropertyChanged("cuotaMarzo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string cuotaAbril {
            get {
                return this.cuotaAbrilField;
            }
            set {
                this.cuotaAbrilField = value;
                this.RaisePropertyChanged("cuotaAbril");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string cuotaMayo {
            get {
                return this.cuotaMayoField;
            }
            set {
                this.cuotaMayoField = value;
                this.RaisePropertyChanged("cuotaMayo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string cuotaJunio {
            get {
                return this.cuotaJunioField;
            }
            set {
                this.cuotaJunioField = value;
                this.RaisePropertyChanged("cuotaJunio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string cuotaJulio {
            get {
                return this.cuotaJulioField;
            }
            set {
                this.cuotaJulioField = value;
                this.RaisePropertyChanged("cuotaJulio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string cuotaAgosto {
            get {
                return this.cuotaAgostoField;
            }
            set {
                this.cuotaAgostoField = value;
                this.RaisePropertyChanged("cuotaAgosto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string cuotaSetiembre {
            get {
                return this.cuotaSetiembreField;
            }
            set {
                this.cuotaSetiembreField = value;
                this.RaisePropertyChanged("cuotaSetiembre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string cuotaOctubre {
            get {
                return this.cuotaOctubreField;
            }
            set {
                this.cuotaOctubreField = value;
                this.RaisePropertyChanged("cuotaOctubre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string cuotaNoviembre {
            get {
                return this.cuotaNoviembreField;
            }
            set {
                this.cuotaNoviembreField = value;
                this.RaisePropertyChanged("cuotaNoviembre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string cuotaDiciembre {
            get {
                return this.cuotaDiciembreField;
            }
            set {
                this.cuotaDiciembreField = value;
                this.RaisePropertyChanged("cuotaDiciembre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/u360/")]
    public partial class detalle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string parte1DetalleGarantiaField;
        
        private string parte2DetalleGarantiaField;
        
        private string parte3DetalleGarantiaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string parte1DetalleGarantia {
            get {
                return this.parte1DetalleGarantiaField;
            }
            set {
                this.parte1DetalleGarantiaField = value;
                this.RaisePropertyChanged("parte1DetalleGarantia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string parte2DetalleGarantia {
            get {
                return this.parte2DetalleGarantiaField;
            }
            set {
                this.parte2DetalleGarantiaField = value;
                this.RaisePropertyChanged("parte2DetalleGarantia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string parte3DetalleGarantia {
            get {
                return this.parte3DetalleGarantiaField;
            }
            set {
                this.parte3DetalleGarantiaField = value;
                this.RaisePropertyChanged("parte3DetalleGarantia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/u360/")]
    public partial class garantia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contratoGarantiaField;
        
        private string tipoGarantiaField;
        
        private string situacionGarantiaField;
        
        private string monedaGarantiaField;
        
        private string importeGarantiaField;
        
        private string fecVinculacionGarantiaField;
        
        private string descripcionGarantiaField;
        
        private detalle[] listaDetallesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string contratoGarantia {
            get {
                return this.contratoGarantiaField;
            }
            set {
                this.contratoGarantiaField = value;
                this.RaisePropertyChanged("contratoGarantia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tipoGarantia {
            get {
                return this.tipoGarantiaField;
            }
            set {
                this.tipoGarantiaField = value;
                this.RaisePropertyChanged("tipoGarantia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string situacionGarantia {
            get {
                return this.situacionGarantiaField;
            }
            set {
                this.situacionGarantiaField = value;
                this.RaisePropertyChanged("situacionGarantia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string monedaGarantia {
            get {
                return this.monedaGarantiaField;
            }
            set {
                this.monedaGarantiaField = value;
                this.RaisePropertyChanged("monedaGarantia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string importeGarantia {
            get {
                return this.importeGarantiaField;
            }
            set {
                this.importeGarantiaField = value;
                this.RaisePropertyChanged("importeGarantia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string fecVinculacionGarantia {
            get {
                return this.fecVinculacionGarantiaField;
            }
            set {
                this.fecVinculacionGarantiaField = value;
                this.RaisePropertyChanged("fecVinculacionGarantia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string descripcionGarantia {
            get {
                return this.descripcionGarantiaField;
            }
            set {
                this.descripcionGarantiaField = value;
                this.RaisePropertyChanged("descripcionGarantia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaDetalles", Order=7)]
        public detalle[] listaDetalles {
            get {
                return this.listaDetallesField;
            }
            set {
                this.listaDetallesField = value;
                this.RaisePropertyChanged("listaDetalles");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/u360/")]
    public partial class interviniente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoIntervinienteField;
        
        private string secuenciaIntervinienteField;
        
        private string codigoClienteIntervinienteField;
        
        private string tipoDOIIntervinienteField;
        
        private string nroDOIIntervinienteField;
        
        private string nombrePaisIntervinienteField;
        
        private string fechaNacIntervinienteField;
        
        private string nombreIntervinienteField;
        
        private string apellidoPatIntervinienteField;
        
        private string apellidoMatIntervinienteField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tipoInterviniente {
            get {
                return this.tipoIntervinienteField;
            }
            set {
                this.tipoIntervinienteField = value;
                this.RaisePropertyChanged("tipoInterviniente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string secuenciaInterviniente {
            get {
                return this.secuenciaIntervinienteField;
            }
            set {
                this.secuenciaIntervinienteField = value;
                this.RaisePropertyChanged("secuenciaInterviniente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codigoClienteInterviniente {
            get {
                return this.codigoClienteIntervinienteField;
            }
            set {
                this.codigoClienteIntervinienteField = value;
                this.RaisePropertyChanged("codigoClienteInterviniente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string tipoDOIInterviniente {
            get {
                return this.tipoDOIIntervinienteField;
            }
            set {
                this.tipoDOIIntervinienteField = value;
                this.RaisePropertyChanged("tipoDOIInterviniente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nroDOIInterviniente {
            get {
                return this.nroDOIIntervinienteField;
            }
            set {
                this.nroDOIIntervinienteField = value;
                this.RaisePropertyChanged("nroDOIInterviniente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string nombrePaisInterviniente {
            get {
                return this.nombrePaisIntervinienteField;
            }
            set {
                this.nombrePaisIntervinienteField = value;
                this.RaisePropertyChanged("nombrePaisInterviniente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string fechaNacInterviniente {
            get {
                return this.fechaNacIntervinienteField;
            }
            set {
                this.fechaNacIntervinienteField = value;
                this.RaisePropertyChanged("fechaNacInterviniente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string nombreInterviniente {
            get {
                return this.nombreIntervinienteField;
            }
            set {
                this.nombreIntervinienteField = value;
                this.RaisePropertyChanged("nombreInterviniente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string apellidoPatInterviniente {
            get {
                return this.apellidoPatIntervinienteField;
            }
            set {
                this.apellidoPatIntervinienteField = value;
                this.RaisePropertyChanged("apellidoPatInterviniente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string apellidoMatInterviniente {
            get {
                return this.apellidoMatIntervinienteField;
            }
            set {
                this.apellidoMatIntervinienteField = value;
                this.RaisePropertyChanged("apellidoMatInterviniente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/u360/")]
    public partial class BodyConsultaPrestamoRs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contratoPrestamoField;
        
        private string codigoClienteField;
        
        private string oficinaTitularField;
        
        private string gestorField;
        
        private string importePrestamoField;
        
        private string plazoPrestamoField;
        
        private string unidadPlazoField;
        
        private string diaPagoField;
        
        private string periodoGraciaField;
        
        private string unidadPeriodoField;
        
        private string monedaPrestamoField;
        
        private string tasaPrestamoField;
        
        private string productoGestionField;
        
        private string subprodPrestamoField;
        
        private string descripcionPrestamoField;
        
        private string tipoDOIField;
        
        private string numeroDOIField;
        
        private string nombreClienteField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string estadoCivilField;
        
        private string sexoField;
        
        private string fechaNacimientoField;
        
        private string paisNacimientoField;
        
        private string nombreGestorField;
        
        private string segmentoClienteField;
        
        private string codigoEstudioField;
        
        private string profesionField;
        
        private string direccionField;
        
        private string correoField;
        
        private string codigoDistritoField;
        
        private string nombreDistritoField;
        
        private string codigoProvinciaField;
        
        private string nombreProvinciaField;
        
        private string codigoDepartamentoField;
        
        private string nombreDepartamentoField;
        
        private string telefono1Field;
        
        private string telefono2Field;
        
        private string telefono3Field;
        
        private string centroTrabajoField;
        
        private string descripcionPuestoField;
        
        private string antEmplField;
        
        private string rvglField;
        
        private string fechaAprobacionField;
        
        private string importeAprobacionField;
        
        private string tipoPlazoField;
        
        private string fechaIngresoField;
        
        private string codigoFuncionarioField;
        
        private string nombreFuncionarioField;
        
        private string porcentajeDeudaField;
        
        private string egresosField;
        
        private string ingresosField;
        
        private string dictamenField;
        
        private string importeDesembolsoField;
        
        private string fechaDesembolsoField;
        
        private interviniente[] listaIntervinientesField;
        
        private garantia[] listaGarantiasField;
        
        private cuotasAdicionales listaCuotasAdicionalesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string contratoPrestamo {
            get {
                return this.contratoPrestamoField;
            }
            set {
                this.contratoPrestamoField = value;
                this.RaisePropertyChanged("contratoPrestamo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
                this.RaisePropertyChanged("codigoCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string oficinaTitular {
            get {
                return this.oficinaTitularField;
            }
            set {
                this.oficinaTitularField = value;
                this.RaisePropertyChanged("oficinaTitular");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string gestor {
            get {
                return this.gestorField;
            }
            set {
                this.gestorField = value;
                this.RaisePropertyChanged("gestor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string importePrestamo {
            get {
                return this.importePrestamoField;
            }
            set {
                this.importePrestamoField = value;
                this.RaisePropertyChanged("importePrestamo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string plazoPrestamo {
            get {
                return this.plazoPrestamoField;
            }
            set {
                this.plazoPrestamoField = value;
                this.RaisePropertyChanged("plazoPrestamo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string unidadPlazo {
            get {
                return this.unidadPlazoField;
            }
            set {
                this.unidadPlazoField = value;
                this.RaisePropertyChanged("unidadPlazo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string diaPago {
            get {
                return this.diaPagoField;
            }
            set {
                this.diaPagoField = value;
                this.RaisePropertyChanged("diaPago");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string periodoGracia {
            get {
                return this.periodoGraciaField;
            }
            set {
                this.periodoGraciaField = value;
                this.RaisePropertyChanged("periodoGracia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string unidadPeriodo {
            get {
                return this.unidadPeriodoField;
            }
            set {
                this.unidadPeriodoField = value;
                this.RaisePropertyChanged("unidadPeriodo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string monedaPrestamo {
            get {
                return this.monedaPrestamoField;
            }
            set {
                this.monedaPrestamoField = value;
                this.RaisePropertyChanged("monedaPrestamo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string tasaPrestamo {
            get {
                return this.tasaPrestamoField;
            }
            set {
                this.tasaPrestamoField = value;
                this.RaisePropertyChanged("tasaPrestamo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string productoGestion {
            get {
                return this.productoGestionField;
            }
            set {
                this.productoGestionField = value;
                this.RaisePropertyChanged("productoGestion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string subprodPrestamo {
            get {
                return this.subprodPrestamoField;
            }
            set {
                this.subprodPrestamoField = value;
                this.RaisePropertyChanged("subprodPrestamo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string descripcionPrestamo {
            get {
                return this.descripcionPrestamoField;
            }
            set {
                this.descripcionPrestamoField = value;
                this.RaisePropertyChanged("descripcionPrestamo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string tipoDOI {
            get {
                return this.tipoDOIField;
            }
            set {
                this.tipoDOIField = value;
                this.RaisePropertyChanged("tipoDOI");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string numeroDOI {
            get {
                return this.numeroDOIField;
            }
            set {
                this.numeroDOIField = value;
                this.RaisePropertyChanged("numeroDOI");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string nombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
                this.RaisePropertyChanged("nombreCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
                this.RaisePropertyChanged("estadoCivil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string paisNacimiento {
            get {
                return this.paisNacimientoField;
            }
            set {
                this.paisNacimientoField = value;
                this.RaisePropertyChanged("paisNacimiento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string nombreGestor {
            get {
                return this.nombreGestorField;
            }
            set {
                this.nombreGestorField = value;
                this.RaisePropertyChanged("nombreGestor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string segmentoCliente {
            get {
                return this.segmentoClienteField;
            }
            set {
                this.segmentoClienteField = value;
                this.RaisePropertyChanged("segmentoCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string codigoEstudio {
            get {
                return this.codigoEstudioField;
            }
            set {
                this.codigoEstudioField = value;
                this.RaisePropertyChanged("codigoEstudio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string profesion {
            get {
                return this.profesionField;
            }
            set {
                this.profesionField = value;
                this.RaisePropertyChanged("profesion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string codigoDistrito {
            get {
                return this.codigoDistritoField;
            }
            set {
                this.codigoDistritoField = value;
                this.RaisePropertyChanged("codigoDistrito");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string nombreDistrito {
            get {
                return this.nombreDistritoField;
            }
            set {
                this.nombreDistritoField = value;
                this.RaisePropertyChanged("nombreDistrito");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string codigoProvincia {
            get {
                return this.codigoProvinciaField;
            }
            set {
                this.codigoProvinciaField = value;
                this.RaisePropertyChanged("codigoProvincia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string nombreProvincia {
            get {
                return this.nombreProvinciaField;
            }
            set {
                this.nombreProvinciaField = value;
                this.RaisePropertyChanged("nombreProvincia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string codigoDepartamento {
            get {
                return this.codigoDepartamentoField;
            }
            set {
                this.codigoDepartamentoField = value;
                this.RaisePropertyChanged("codigoDepartamento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string nombreDepartamento {
            get {
                return this.nombreDepartamentoField;
            }
            set {
                this.nombreDepartamentoField = value;
                this.RaisePropertyChanged("nombreDepartamento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string telefono1 {
            get {
                return this.telefono1Field;
            }
            set {
                this.telefono1Field = value;
                this.RaisePropertyChanged("telefono1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string telefono2 {
            get {
                return this.telefono2Field;
            }
            set {
                this.telefono2Field = value;
                this.RaisePropertyChanged("telefono2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string telefono3 {
            get {
                return this.telefono3Field;
            }
            set {
                this.telefono3Field = value;
                this.RaisePropertyChanged("telefono3");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string centroTrabajo {
            get {
                return this.centroTrabajoField;
            }
            set {
                this.centroTrabajoField = value;
                this.RaisePropertyChanged("centroTrabajo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string descripcionPuesto {
            get {
                return this.descripcionPuestoField;
            }
            set {
                this.descripcionPuestoField = value;
                this.RaisePropertyChanged("descripcionPuesto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string antEmpl {
            get {
                return this.antEmplField;
            }
            set {
                this.antEmplField = value;
                this.RaisePropertyChanged("antEmpl");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string rvgl {
            get {
                return this.rvglField;
            }
            set {
                this.rvglField = value;
                this.RaisePropertyChanged("rvgl");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string fechaAprobacion {
            get {
                return this.fechaAprobacionField;
            }
            set {
                this.fechaAprobacionField = value;
                this.RaisePropertyChanged("fechaAprobacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string importeAprobacion {
            get {
                return this.importeAprobacionField;
            }
            set {
                this.importeAprobacionField = value;
                this.RaisePropertyChanged("importeAprobacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string tipoPlazo {
            get {
                return this.tipoPlazoField;
            }
            set {
                this.tipoPlazoField = value;
                this.RaisePropertyChanged("tipoPlazo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
                this.RaisePropertyChanged("fechaIngreso");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string codigoFuncionario {
            get {
                return this.codigoFuncionarioField;
            }
            set {
                this.codigoFuncionarioField = value;
                this.RaisePropertyChanged("codigoFuncionario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string nombreFuncionario {
            get {
                return this.nombreFuncionarioField;
            }
            set {
                this.nombreFuncionarioField = value;
                this.RaisePropertyChanged("nombreFuncionario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string porcentajeDeuda {
            get {
                return this.porcentajeDeudaField;
            }
            set {
                this.porcentajeDeudaField = value;
                this.RaisePropertyChanged("porcentajeDeuda");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string egresos {
            get {
                return this.egresosField;
            }
            set {
                this.egresosField = value;
                this.RaisePropertyChanged("egresos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string ingresos {
            get {
                return this.ingresosField;
            }
            set {
                this.ingresosField = value;
                this.RaisePropertyChanged("ingresos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string dictamen {
            get {
                return this.dictamenField;
            }
            set {
                this.dictamenField = value;
                this.RaisePropertyChanged("dictamen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string importeDesembolso {
            get {
                return this.importeDesembolsoField;
            }
            set {
                this.importeDesembolsoField = value;
                this.RaisePropertyChanged("importeDesembolso");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string fechaDesembolso {
            get {
                return this.fechaDesembolsoField;
            }
            set {
                this.fechaDesembolsoField = value;
                this.RaisePropertyChanged("fechaDesembolso");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaIntervinientes", Order=55)]
        public interviniente[] listaIntervinientes {
            get {
                return this.listaIntervinientesField;
            }
            set {
                this.listaIntervinientesField = value;
                this.RaisePropertyChanged("listaIntervinientes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaGarantias", Order=56)]
        public garantia[] listaGarantias {
            get {
                return this.listaGarantiasField;
            }
            set {
                this.listaGarantiasField = value;
                this.RaisePropertyChanged("listaGarantias");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public cuotasAdicionales listaCuotasAdicionales {
            get {
                return this.listaCuotasAdicionalesField;
            }
            set {
                this.listaCuotasAdicionalesField = value;
                this.RaisePropertyChanged("listaCuotasAdicionales");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/u360/")]
    public partial class consultaPrestamoRs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ctHeaderRs headerField;
        
        private BodyConsultaPrestamoRs bodyField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ctHeaderRs header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("header");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BodyConsultaPrestamoRs body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/ps9/")]
    public partial class ctHeaderRs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descripcionField;
        
        private string avisoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string aviso {
            get {
                return this.avisoField;
            }
            set {
                this.avisoField = value;
                this.RaisePropertyChanged("aviso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/u360/")]
    public partial class BodyConsultaPrestamoRq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoCuentaClienteField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoCuentaCliente {
            get {
                return this.codigoCuentaClienteField;
            }
            set {
                this.codigoCuentaClienteField = value;
                this.RaisePropertyChanged("codigoCuentaCliente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/u360/")]
    public partial class consultaPrestamoRq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ctHeaderRq headerField;
        
        private BodyConsultaPrestamoRq bodyField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ctHeaderRq header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("header");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BodyConsultaPrestamoRq body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/b402/")]
    public partial class BodyConsultaSaldosRs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string saldoDisponibleField;
        
        private string saldoContableField;
        
        private string saldoActualField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string saldoDisponible {
            get {
                return this.saldoDisponibleField;
            }
            set {
                this.saldoDisponibleField = value;
                this.RaisePropertyChanged("saldoDisponible");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string saldoContable {
            get {
                return this.saldoContableField;
            }
            set {
                this.saldoContableField = value;
                this.RaisePropertyChanged("saldoContable");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string saldoActual {
            get {
                return this.saldoActualField;
            }
            set {
                this.saldoActualField = value;
                this.RaisePropertyChanged("saldoActual");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/b402/")]
    public partial class consultaSaldosRs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ctHeaderRs headerField;
        
        private BodyConsultaSaldosRs bodyField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ctHeaderRs header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("header");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BodyConsultaSaldosRs body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/b402/")]
    public partial class BodyConsultaSaldosRq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoCuentaClienteField;
        
        private string opcionField;
        
        private string cobComisionField;
        
        private string papelField;
        
        private string libreField;
        
        private string tarjetaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoCuentaCliente {
            get {
                return this.codigoCuentaClienteField;
            }
            set {
                this.codigoCuentaClienteField = value;
                this.RaisePropertyChanged("codigoCuentaCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string opcion {
            get {
                return this.opcionField;
            }
            set {
                this.opcionField = value;
                this.RaisePropertyChanged("opcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cobComision {
            get {
                return this.cobComisionField;
            }
            set {
                this.cobComisionField = value;
                this.RaisePropertyChanged("cobComision");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string papel {
            get {
                return this.papelField;
            }
            set {
                this.papelField = value;
                this.RaisePropertyChanged("papel");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string libre {
            get {
                return this.libreField;
            }
            set {
                this.libreField = value;
                this.RaisePropertyChanged("libre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string tarjeta {
            get {
                return this.tarjetaField;
            }
            set {
                this.tarjetaField = value;
                this.RaisePropertyChanged("tarjeta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaSaldos_Input {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/b402/", Order=0)]
        public Presto.BBVA.ServicioBanco.consultaSaldosRq consultaSaldosRq;
        
        public consultaSaldos_Input() {
        }
        
        public consultaSaldos_Input(Presto.BBVA.ServicioBanco.consultaSaldosRq consultaSaldosRq) {
            this.consultaSaldosRq = consultaSaldosRq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaSaldos_Output {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/b402/", Order=0)]
        public Presto.BBVA.ServicioBanco.consultaSaldosRs consultaSaldosRs;
        
        public consultaSaldos_Output() {
        }
        
        public consultaSaldos_Output(Presto.BBVA.ServicioBanco.consultaSaldosRs consultaSaldosRs) {
            this.consultaSaldosRs = consultaSaldosRs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaPrestamo_Input {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/u360/", Order=0)]
        public Presto.BBVA.ServicioBanco.consultaPrestamoRq consultaPrestamoRq;
        
        public consultaPrestamo_Input() {
        }
        
        public consultaPrestamo_Input(Presto.BBVA.ServicioBanco.consultaPrestamoRq consultaPrestamoRq) {
            this.consultaPrestamoRq = consultaPrestamoRq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaPrestamo_Output {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://grupobbva.com.pe/portalinmobiliario/xsd/u360/", Order=0)]
        public Presto.BBVA.ServicioBanco.consultaPrestamoRs consultaPrestamoRs;
        
        public consultaPrestamo_Output() {
        }
        
        public consultaPrestamo_Output(Presto.BBVA.ServicioBanco.consultaPrestamoRs consultaPrestamoRs) {
            this.consultaPrestamoRs = consultaPrestamoRs;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MS_BBVA_PORTAL_INMOBILIARIOPortTypeChannel : Presto.BBVA.ServicioBanco.MS_BBVA_PORTAL_INMOBILIARIOPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MS_BBVA_PORTAL_INMOBILIARIOPortTypeClient : System.ServiceModel.ClientBase<Presto.BBVA.ServicioBanco.MS_BBVA_PORTAL_INMOBILIARIOPortType>, Presto.BBVA.ServicioBanco.MS_BBVA_PORTAL_INMOBILIARIOPortType {
        
        public MS_BBVA_PORTAL_INMOBILIARIOPortTypeClient() {
        }
        
        public MS_BBVA_PORTAL_INMOBILIARIOPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MS_BBVA_PORTAL_INMOBILIARIOPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MS_BBVA_PORTAL_INMOBILIARIOPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MS_BBVA_PORTAL_INMOBILIARIOPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presto.BBVA.ServicioBanco.consultaSaldos_Output Presto.BBVA.ServicioBanco.MS_BBVA_PORTAL_INMOBILIARIOPortType.consultaSaldos(Presto.BBVA.ServicioBanco.consultaSaldos_Input request) {
            return base.Channel.consultaSaldos(request);
        }
        
        public Presto.BBVA.ServicioBanco.consultaSaldosRs consultaSaldos(Presto.BBVA.ServicioBanco.consultaSaldosRq consultaSaldosRq) {
            Presto.BBVA.ServicioBanco.consultaSaldos_Input inValue = new Presto.BBVA.ServicioBanco.consultaSaldos_Input();
            inValue.consultaSaldosRq = consultaSaldosRq;
            Presto.BBVA.ServicioBanco.consultaSaldos_Output retVal = ((Presto.BBVA.ServicioBanco.MS_BBVA_PORTAL_INMOBILIARIOPortType)(this)).consultaSaldos(inValue);
            return retVal.consultaSaldosRs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Presto.BBVA.ServicioBanco.consultaPrestamo_Output Presto.BBVA.ServicioBanco.MS_BBVA_PORTAL_INMOBILIARIOPortType.consultaPrestamo(Presto.BBVA.ServicioBanco.consultaPrestamo_Input request) {
            return base.Channel.consultaPrestamo(request);
        }
        
        public Presto.BBVA.ServicioBanco.consultaPrestamoRs consultaPrestamo(Presto.BBVA.ServicioBanco.consultaPrestamoRq consultaPrestamoRq) {
            Presto.BBVA.ServicioBanco.consultaPrestamo_Input inValue = new Presto.BBVA.ServicioBanco.consultaPrestamo_Input();
            inValue.consultaPrestamoRq = consultaPrestamoRq;
            Presto.BBVA.ServicioBanco.consultaPrestamo_Output retVal = ((Presto.BBVA.ServicioBanco.MS_BBVA_PORTAL_INMOBILIARIOPortType)(this)).consultaPrestamo(inValue);
            return retVal.consultaPrestamoRs;
        }
    }
}
