//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acta
    {
        public Acta()
        {
            this.DetalleActas = new HashSet<DetalleActa>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public Nullable<int> IdTipoActa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual TipoActa TipoActa { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<DetalleActa> DetalleActas { get; set; }
    }
}
