//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlDeProceso
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Medidas1 { get; set; }
        public string Especificaciones { get; set; }
        public Nullable<int> Medidas2 { get; set; }
        public Nullable<int> IdProgramacion { get; set; }
        public string Elementos { get; set; }
        public Nullable<bool> Soldadura { get; set; }
        public string Nivel { get; set; }
        public Nullable<bool> ExcesoSoldadura { get; set; }
        public Nullable<bool> ManchasSoldadura { get; set; }
        public string DescripcionDelProblema { get; set; }
        public string AccionesNoConforme { get; set; }
        public Nullable<bool> VoBo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ProgramacionTarea ProgramacionTarea { get; set; }
        public virtual User User { get; set; }
    }
}
