//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleActa
    {
        public DetalleActa()
        {
            this.MaterialesActaDetalles = new HashSet<MaterialesActaDetalle>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdActa { get; set; }
        public Nullable<int> IdTipoMontaje { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<bool> Cumple { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
    
        public virtual Acta Acta { get; set; }
        public virtual TipoMOntaje TipoMOntaje { get; set; }
        public virtual ICollection<MaterialesActaDetalle> MaterialesActaDetalles { get; set; }
    }
}
