//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.Actas = new HashSet<Acta>();
            this.ControlEntregasInternas = new HashSet<ControlEntregasInterna>();
            this.Modificaciones = new HashSet<Modificacione>();
            this.Procesos = new HashSet<Proceso>();
            this.ProgramacionTareas = new HashSet<ProgramacionTarea>();
            this.RemisionesExternas = new HashSet<RemisionesExterna>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Id_empresa { get; set; }
        public Nullable<int> Id_Bodega { get; set; }
        public Nullable<int> IdTipoMovimiento { get; set; }
        public Nullable<int> DiasValidez { get; set; }
        public Nullable<decimal> TotalSub { get; set; }
        public Nullable<decimal> Total_Descuento { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string NotasInternas { get; set; }
        public string Notas { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdDocumentoAnterior { get; set; }
        public Nullable<int> EstadoDocumento { get; set; }
        public Nullable<int> IdFormaPago { get; set; }
    
        public virtual ICollection<Acta> Actas { get; set; }
        public virtual ICollection<ControlEntregasInterna> ControlEntregasInternas { get; set; }
        public virtual EstadoDocumento EstadoDocumento1 { get; set; }
        public virtual FomaDePago FomaDePago { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Modificacione> Modificaciones { get; set; }
        public virtual ICollection<Proceso> Procesos { get; set; }
        public virtual ICollection<ProgramacionTarea> ProgramacionTareas { get; set; }
        public virtual ICollection<RemisionesExterna> RemisionesExternas { get; set; }
    }
}
