//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPTO
    {
        public DPTO()
        {
            this.Municipios = new HashSet<Municipio>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdPais { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual ICollection<Municipio> Municipios { get; set; }
    }
}
