//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int ID { get; set; }
        public Nullable<int> IdItem { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public Nullable<int> CantidadAnterior { get; set; }
        public Nullable<int> CantidadDespachada { get; set; }
        public Nullable<int> CantidadDisponible { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
