//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.DetalleDocumentoes = new HashSet<DetalleDocumento>();
            this.FotosItems = new HashSet<FotosItem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Subgrupo { get; set; }
        public Nullable<int> IdIva { get; set; }
        public Nullable<int> MaxDescuento { get; set; }
        public Nullable<int> CantidadMinima { get; set; }
        public Nullable<int> CantidadMaxima { get; set; }
        public Nullable<int> Anulado { get; set; }
        public Nullable<int> NumeroDecimales { get; set; }
        public string Notas { get; set; }
        public Nullable<int> IdColor { get; set; }
        public string Modelo { get; set; }
        public string NroSerie { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public Nullable<int> ManejaStock { get; set; }
        public Nullable<int> IdTalla { get; set; }
        public Nullable<int> StockActual { get; set; }
        public Nullable<int> DiasReposicion { get; set; }
        public string CalificacionABC { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual ICollection<DetalleDocumento> DetalleDocumentoes { get; set; }
        public virtual ICollection<FotosItem> FotosItems { get; set; }
        public virtual Iva Iva { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual SubGrupo SubGrupo1 { get; set; }
        public virtual Talla Talla { get; set; }
        public virtual User User { get; set; }
    }
}
