//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        public Marca()
        {
            this.Items = new HashSet<Item>();
            this.Grupoes = new HashSet<Grupo>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public int IdEmpresa { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Grupo> Grupoes { get; set; }
    }
}
