//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiale
    {
        public Materiale()
        {
            this.MaterialesActaDetalles = new HashSet<MaterialesActaDetalle>();
            this.MaterialesActaDetalles1 = new HashSet<MaterialesActaDetalle>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<MaterialesActaDetalle> MaterialesActaDetalles { get; set; }
        public virtual ICollection<MaterialesActaDetalle> MaterialesActaDetalles1 { get; set; }
    }
}
