//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modificacione
    {
        public int ID { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public Nullable<int> SolicitaCambio { get; set; }
        public Nullable<int> IdMotivoModificacion { get; set; }
        public string Descripcion { get; set; }
        public string Actividades { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual MotivoModificacione MotivoModificacione { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
