//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfile
    {
        public long Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual User User { get; set; }
    }
}
