//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int ID { get; set; }
        public Nullable<int> TipoDocumento { get; set; }
        public string NroDocumento { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public int CiudadResidencia { get; set; }
        public string Nota { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> TipoPersona { get; set; }
        public Nullable<bool> RegimenSimplificado { get; set; }
        public int IdEmpesa { get; set; }
        public Nullable<bool> Autoretenedores { get; set; }
        public Nullable<bool> AplicaAIU { get; set; }
        public string Contacto { get; set; }
        public Nullable<bool> RecibirEmail { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual TipoDocumento TipoDocumento1 { get; set; }
        public virtual TipoPersona TipoPersona1 { get; set; }
    }
}
