//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso
    {
        public Proceso()
        {
            this.ProgramacionTareas = new HashSet<ProgramacionTarea>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdTipoProceso { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual TipoProceso TipoProceso { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ProgramacionTarea> ProgramacionTareas { get; set; }
    }
}
