//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramacionTarea
    {
        public ProgramacionTarea()
        {
            this.ControlDeProcesos = new HashSet<ControlDeProceso>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdResponsable { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdProceso { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
    
        public virtual ICollection<ControlDeProceso> ControlDeProcesos { get; set; }
        public virtual Documento Documento { get; set; }
        public virtual Proceso Proceso { get; set; }
        public virtual User User { get; set; }
    }
}
