//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecibosCaja
    {
        public int Id { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Notas { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdUsuarioVende { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
