//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemisionesExterna
    {
        public RemisionesExterna()
        {
            this.DetalleRemisiones = new HashSet<DetalleRemisione>();
        }
    
        public int ID { get; set; }
        public int IdOrdenProduccion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdUsuarioDespachador { get; set; }
        public Nullable<int> IdTransportador { get; set; }
        public string RecibidoPot { get; set; }
    
        public virtual ICollection<DetalleRemisione> DetalleRemisiones { get; set; }
        public virtual Documento Documento { get; set; }
        public virtual User User { get; set; }
    }
}
