//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generals.business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Actas = new HashSet<Acta>();
            this.Bodegas = new HashSet<Bodega>();
            this.Colors = new HashSet<Color>();
            this.ControlDeProcesos = new HashSet<ControlDeProceso>();
            this.ControlEntregasInternas = new HashSet<ControlEntregasInterna>();
            this.Documentos = new HashSet<Documento>();
            this.Items = new HashSet<Item>();
            this.Ivas = new HashSet<Iva>();
            this.Marcas = new HashSet<Marca>();
            this.Modificaciones = new HashSet<Modificacione>();
            this.Modificaciones1 = new HashSet<Modificacione>();
            this.Perfiles = new HashSet<Perfile>();
            this.Procesos = new HashSet<Proceso>();
            this.ProgramacionTareas = new HashSet<ProgramacionTarea>();
            this.RecibosCajas = new HashSet<RecibosCaja>();
            this.RecibosCajas1 = new HashSet<RecibosCaja>();
            this.RemisionesExternas = new HashSet<RemisionesExterna>();
            this.SubGrupoes = new HashSet<SubGrupo>();
            this.Tallas = new HashSet<Talla>();
            this.TipoMovimientoes = new HashSet<TipoMovimiento>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Cedula { get; set; }
        public string Nombres { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> FechaSistema { get; set; }
        public string Telefono { get; set; }
    
        public virtual ICollection<Acta> Actas { get; set; }
        public virtual ICollection<Bodega> Bodegas { get; set; }
        public virtual ICollection<Color> Colors { get; set; }
        public virtual ICollection<ControlDeProceso> ControlDeProcesos { get; set; }
        public virtual ICollection<ControlEntregasInterna> ControlEntregasInternas { get; set; }
        public virtual ICollection<Documento> Documentos { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Iva> Ivas { get; set; }
        public virtual ICollection<Marca> Marcas { get; set; }
        public virtual ICollection<Modificacione> Modificaciones { get; set; }
        public virtual ICollection<Modificacione> Modificaciones1 { get; set; }
        public virtual ICollection<Perfile> Perfiles { get; set; }
        public virtual ICollection<Proceso> Procesos { get; set; }
        public virtual ICollection<ProgramacionTarea> ProgramacionTareas { get; set; }
        public virtual ICollection<RecibosCaja> RecibosCajas { get; set; }
        public virtual ICollection<RecibosCaja> RecibosCajas1 { get; set; }
        public virtual ICollection<RemisionesExterna> RemisionesExternas { get; set; }
        public virtual ICollection<SubGrupo> SubGrupoes { get; set; }
        public virtual ICollection<Talla> Tallas { get; set; }
        public virtual ICollection<TipoMovimiento> TipoMovimientoes { get; set; }
    }
}
